=begin
#Azure OpenAI Service API

#Azure OpenAI APIs for completions and search

The version of the OpenAPI document: 2023-05-15

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

# Common files
require 'azureai_client/api_client'
require 'azureai_client/api_error'
require 'azureai_client/version'
require 'azureai_client/configuration'

# Models
require 'azureai_client/models/chat_completions_create200_response'
require 'azureai_client/models/chat_completions_create200_response_choices_inner'
require 'azureai_client/models/chat_completions_create200_response_choices_inner_message'
require 'azureai_client/models/chat_completions_create200_response_usage'
require 'azureai_client/models/chat_completions_create_request'
require 'azureai_client/models/chat_completions_create_request_messages_inner'
require 'azureai_client/models/chat_completions_create_request_stop'
require 'azureai_client/models/completions_create200_response'
require 'azureai_client/models/completions_create200_response_choices_inner'
require 'azureai_client/models/completions_create200_response_choices_inner_logprobs'
require 'azureai_client/models/completions_create200_response_usage'
require 'azureai_client/models/completions_create_request'
require 'azureai_client/models/completions_create_request_prompt'
require 'azureai_client/models/completions_create_request_stop'
require 'azureai_client/models/embeddings_create200_response'
require 'azureai_client/models/embeddings_create200_response_data_inner'
require 'azureai_client/models/embeddings_create200_response_usage'
require 'azureai_client/models/embeddings_create_request'
require 'azureai_client/models/embeddings_create_request_input'
require 'azureai_client/models/error_response'
require 'azureai_client/models/error_response_error'

# APIs
require 'azureai_client/api/default_api'

module AzureAIClient
  class << self
    # Customize default settings for the SDK using block.
    #   AzureAIClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
